# Define a Service for the Stock Manager application
apiVersion: v1
kind: Service
metadata:
  name: stockmanager
  labels:
    app: stockmanager
spec:
  type: NodePort
  selector:
    app: stockmanager
  ports:
  - protocol: TCP
    port: 8030
    name: http

# Define a Deployment for the Stock Manager application
apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockmanager
spec:
  selector:
    matchLabels:
      app: stockmanager
  replicas: 1 # Number of replicas
  template:
    metadata:
      labels:
        app: stockmanager
    spec:
      containers:
      - name: stockmanager
        image: task/stockmanager:latest # Docker image to use
        ports:
        - containerPort: 8030 # Port exposed by the container
        livenessProbe: # Liveness probe to check the health of the application
          httpGet:
            path: /health
            port: 8030
          initialDelaySeconds: 30
          timeoutSeconds: 1

